---
center_weight: 3000 # N
N: 1.0 # flight load factor (L/W)
span: 30 # m
wing_area: 54.8 # m^2
# taper_ratio: .5
V: 20 # m/s flight speed
p: 36.2 # kg/m^3air density
R_outer: .1 # m outer radius of tube spar
R_inner: .1
length: 20 # m length
G: 4550.5 # Mpa torsion stiffness  modulus
E: 140000 #127500 # Mpa bending stiffness modulus
allowed_ax_stress:  295 #255 # Mpa max allowable axial stress (this number should be knocked down from the true value)
deflection: 5 # m max allowed bending deflection of spar
delta: .001 # integration step size
layup_density: 1500 # kg/m^3 density of carbon fiber layup
...